// LOCAFELO TASK CATEGORIES - Individual Quick Help Categories
// Focus: Individual helping individual for quick local needs
// All categories have "Other" subcategory for flexibility

export interface TaskCategory {
  id: string;
  name: string;
  description: string;
  emoji: string;
  subSkills: string[];
  priority?: number;
}

export const HELPER_TASK_CATEGORIES: TaskCategory[] = [
  // ===== TOP PRIORITY CATEGORIES (Quick Individual Help) =====
  {
    id: 'luggage-help',
    name: 'Luggage Help',
    description: 'Carry luggage, bags, heavy items',
    emoji: '🧳',
    priority: 1,
    subSkills: [
      'Carry luggage',
      'Airport luggage help',
      'Railway station help',
      'Metro station help',
      'Load/unload bags',
      'Heavy item carrying',
      'Other',
    ],
  },
  {
    id: 'delivery',
    name: 'Delivery',
    description: 'Pick up, deliver, bring something',
    emoji: '🚚',
    priority: 1,
    subSkills: [
      'Pickup & delivery',
      'Bring documents',
      'Get groceries',
      'Fetch items',
      'Medicine pickup',
      'Food pickup',
      'Other',
    ],
  },
  {
    id: 'drop-pickup',
    name: 'Drop Me / Pick Me',
    description: 'Drop to office, pick from station, short rides',
    emoji: '🚗',
    priority: 1,
    subSkills: [
      'Drop to office',
      'Pick from metro',
      'Airport pickup/drop',
      'Railway station ride',
      'Short distance ride',
      'School pickup/drop',
      'Other',
    ],
  },
  {
    id: 'tech-help',
    name: 'Tech Help',
    description: 'Computer, laptop, mobile help',
    emoji: '💻',
    priority: 1,
    subSkills: [
      'Computer repair',
      'Laptop troubleshoot',
      'Mobile help',
      'Software installation',
      'WiFi setup',
      'Printer setup',
      'Data recovery',
      'Virus removal',
      'Other',
    ],
  },
  {
    id: 'medical',
    name: 'Medical Help',
    description: 'Doctor visit, medicine pickup, medical help',
    emoji: '⚕️',
    priority: 1,
    subSkills: [
      'Doctor visit companion',
      'Medicine pickup',
      'Pharmacy run',
      'Medical report collection',
      'Hospital visit help',
      'Blood test booking',
      'Appointment booking',
      'Other',
    ],
  },
  {
    id: 'cleaning',
    name: 'Cleaning',
    description: 'House cleaning, room cleaning',
    emoji: '🧹',
    priority: 1,
    subSkills: [
      'House cleaning',
      'Room cleaning',
      'Kitchen cleaning',
      'Bathroom cleaning',
      'Window cleaning',
      'Other',
    ],
  },
  {
    id: 'cooking',
    name: 'Cooking',
    description: 'Home cooking, meal prep',
    emoji: '🍳',
    priority: 1,
    subSkills: [
      'Home cooking',
      'Meal prep',
      'North Indian',
      'South Indian',
      'Chinese food',
      'Continental',
      'Tiffin service',
      'Other',
    ],
  },
  {
    id: 'stay',
    name: 'Stay',
    description: 'Room, PG, accommodation',
    emoji: '🏠',
    priority: 1,
    subSkills: [
      'PG for men',
      'PG for women',
      'Bachelor room (men)',
      'Bachelor room (women)',
      'Shared room (men)',
      'Shared room (women)',
      'Single room (men)',
      'Single room (women)',
      'Flat sharing (men)',
      'Flat sharing (women)',
      'Homestay',
      'Guest room',
      'Short term stay',
      'Long term stay',
      'Other',
    ],
  },
  {
    id: 'mentorship',
    name: 'Mentorship',
    description: 'Career guidance, advice',
    emoji: '🎯',
    priority: 1,
    subSkills: [
      'Career mentoring',
      'Resume review',
      'Interview prep',
      'Job search help',
      'Skill guidance',
      'Other',
    ],
  },
  {
    id: 'moving-help',
    name: 'Moving Help',
    description: 'House shifting, moving help',
    emoji: '📦',
    priority: 1,
    subSkills: [
      'House shifting',
      'Packing help',
      'Furniture moving',
      'Loading/unloading',
      'Unpacking help',
      'Other',
    ],
  },
  {
    id: 'plumbing',
    name: 'Plumbing',
    description: 'Tap repairs, pipe leaks',
    emoji: '🚰',
    priority: 1,
    subSkills: [
      'Tap repair',
      'Pipe leak fixing',
      'Drainage cleaning',
      'Geyser repair',
      'Bathroom plumbing',
      'Kitchen plumbing',
      'Toilet repair',
      'Other',
    ],
  },
  {
    id: 'electrical',
    name: 'Electrical Repair',
    description: 'Wiring, switches, appliance repair',
    emoji: '⚡',
    priority: 1,
    subSkills: [
      'Switch/socket repair',
      'Fan repair',
      'Light fixture',
      'Wiring work',
      'AC repair',
      'Refrigerator repair',
      'Washing machine repair',
      'Microwave repair',
      'Water purifier repair',
      'Geyser repair',
      'Mixer grinder repair',
      'Induction repair',
      'TV repair',
      'Iron repair',
      'Other',
    ],
  },
  {
    id: 'carpentry',
    name: 'Carpentry',
    description: 'Furniture repair, woodwork',
    emoji: '🪚',
    priority: 1,
    subSkills: [
      'Furniture repair',
      'Door repair',
      'Window repair',
      'Shelf installation',
      'Wood polishing',
      'Bed repair',
      'Wardrobe repair',
      'Other',
    ],
  },
  {
    id: 'caretaker',
    name: 'Caretaker',
    description: 'Elderly care, patient care',
    emoji: '👨‍⚕️',
    priority: 1,
    subSkills: [
      'Elderly care',
      'Patient caretaker',
      'Post-surgery care',
      'Daily care help',
      'Medicine reminders',
      'Mobility help',
      'Meal preparation',
      'Night caretaker',
      'Other',
    ],
  },
  {
    id: 'tutoring',
    name: 'Tutoring',
    description: 'Subject tutoring, teaching',
    emoji: '📚',
    priority: 1,
    subSkills: [
      'Math tutoring',
      'Science tutoring',
      'English tutoring',
      'All subjects',
      'Exam preparation',
      'Home tuition',
      'Other',
    ],
  },
  {
    id: 'language-learning',
    name: 'Language Learning',
    description: 'English, languages',
    emoji: '🗣️',
    priority: 1,
    subSkills: [
      'English speaking',
      'Conversation practice',
      'Hindi learning',
      'Regional languages',
      'Other',
    ],
  },
  {
    id: 'civil-works',
    name: 'Civil Works',
    description: 'House repairs, renovation',
    emoji: '🏗️',
    priority: 1,
    subSkills: [
      'House repair',
      'Wall repair',
      'Floor tiling',
      'Wall tiling',
      'Plastering',
      'Waterproofing',
      'Ceiling work',
      'Painting work',
      'Other',
    ],
  },
  {
    id: 'driving',
    name: 'Driving',
    description: 'Driving help, learning',
    emoji: '🚙',
    priority: 1,
    subSkills: [
      'Personal driver',
      'Part-time driver',
      'Driving lessons',
      'License help',
      'Car driving',
      'Bike driving',
      'Other',
    ],
  },
  {
    id: 'photography',
    name: 'Photography',
    description: 'Photos, videos',
    emoji: '📷',
    priority: 1,
    subSkills: [
      'Event photography',
      'Portrait photography',
      'Product photography',
      'Video recording',
      'Photo editing',
      'Other',
    ],
  },
  {
    id: 'design-help',
    name: 'Design Help',
    description: 'Graphics, logos, editing',
    emoji: '🖌️',
    priority: 1,
    subSkills: [
      'Logo design',
      'Poster design',
      'Video editing',
      'Photo editing',
      'Social media graphics',
      'Other',
    ],
  },
  {
    id: 'tax-help',
    name: 'Chartered Accountant',
    description: 'CA services, tax, GST, company registration',
    emoji: '📊',
    priority: 1,
    subSkills: [
      'Income tax filing',
      'GST registration',
      'GST filing',
      'TDS filing',
      'Company incorporation',
      'Auditing services',
      'Book keeping',
      'Accounting services',
      'Tax planning',
      'Financial consulting',
      'ITR filing',
      'ROC compliance',
      'Payroll management',
      'LLP registration',
      'Partnership deed',
      'MSME registration',
      'Import/Export code',
      'Other',
    ],
  },
  {
    id: 'writing-help',
    name: 'Writing Help',
    description: 'Content writing, documentation',
    emoji: '✍️',
    priority: 1,
    subSkills: [
      'Content writing',
      'Resume writing',
      'Document writing',
      'Translation',
      'Proofreading',
      'Other',
    ],
  },
  {
    id: 'pest-control',
    name: 'Pest Control',
    description: 'Pest control help',
    emoji: '🦟',
    priority: 1,
    subSkills: [
      'General pest control',
      'Cockroach control',
      'Termite treatment',
      'Bed bug treatment',
      'Rat control',
      'Other',
    ],
  },

  // ===== ADDITIONAL HELP CATEGORIES =====
  {
    id: 'partner-needed',
    name: 'Partner Needed',
    description: 'Gym buddy, sports partner',
    emoji: '🤝',
    subSkills: [
      'Gym partner',
      'Badminton partner',
      'Tennis partner',
      'Cricket partner',
      'Football partner',
      'Running partner',
      'Cycling partner',
      'Other',
    ],
  },
  {
    id: 'errands',
    name: 'Errands',
    description: 'Queue standing, bank work',
    emoji: '🏃',
    subSkills: [
      'Queue standing',
      'Bank work',
      'Post office',
      'Document submission',
      'Government office',
      'Bill payment',
      'Other',
    ],
  },
  {
    id: 'laundry',
    name: 'Laundry',
    description: 'Washing, ironing',
    emoji: '🧺',
    subSkills: [
      'Washing clothes',
      'Ironing',
      'Dry clean pickup',
      'Other',
    ],
  },
  {
    id: 'grocery-shopping',
    name: 'Grocery Shopping',
    description: 'Buy groceries, shopping',
    emoji: '🛒',
    subSkills: [
      'Grocery shopping',
      'Vegetable shopping',
      'Fruit shopping',
      'Market shopping',
      'Other',
    ],
  },
  {
    id: 'pet-care',
    name: 'Pet Care',
    description: 'Dog walking, pet sitting',
    emoji: '🐕',
    subSkills: [
      'Dog walking',
      'Pet sitting',
      'Pet feeding',
      'Vet visit help',
      'Other',
    ],
  },
  {
    id: 'painting',
    name: 'Painting',
    description: 'Wall painting, room painting',
    emoji: '🎨',
    subSkills: [
      'Room painting',
      'Wall painting',
      'Touch-up work',
      'Other',
    ],
  },
  {
    id: 'installation',
    name: 'Installation',
    description: 'Furniture assembly, setup',
    emoji: '🔨',
    subSkills: [
      'Furniture assembly',
      'TV mounting',
      'Curtain installation',
      'Shelf setup',
      'Other',
    ],
  },
  {
    id: 'salon-home',
    name: 'Salon at Home',
    description: 'Haircut, styling',
    emoji: '💇',
    subSkills: [
      'Haircut (men)',
      'Haircut (women)',
      'Beard trim',
      'Hair styling',
      'Other',
    ],
  },
  {
    id: 'beauty-makeup',
    name: 'Beauty & Makeup',
    description: 'Makeup, beauty services',
    emoji: '💄',
    subSkills: [
      'Makeup',
      'Mehndi/Henna',
      'Waxing',
      'Threading',
      'Other',
    ],
  },
  {
    id: 'massage',
    name: 'Massage',
    description: 'Body massage, relaxation',
    emoji: '💆',
    subSkills: [
      'Body massage',
      'Head massage',
      'Foot massage',
      'Other',
    ],
  },
  {
    id: 'babysitting',
    name: 'Babysitting',
    description: 'Childcare, babysitting',
    emoji: '👶',
    subSkills: [
      'Babysitting',
      'Child care',
      'After-school care',
      'Other',
    ],
  },
  {
    id: 'music-dance',
    name: 'Music & Dance',
    description: 'Music, dance lessons',
    emoji: '🎵',
    subSkills: [
      'Guitar lessons',
      'Singing lessons',
      'Dance lessons',
      'Keyboard lessons',
      'Other',
    ],
  },
  {
    id: 'legal-help',
    name: 'Legal Help',
    description: 'Legal consultation',
    emoji: '⚖️',
    subSkills: [
      'Legal consultation',
      'Document help',
      'Property matters',
      'Other',
    ],
  },
  {
    id: 'event-help',
    name: 'Event Help',
    description: 'Party, event help',
    emoji: '🎉',
    subSkills: [
      'Birthday planning',
      'Party help',
      'Event decoration',
      'Other',
    ],
  },
  {
    id: 'gardening',
    name: 'Gardening',
    description: 'Garden work, plant care',
    emoji: '🪴',
    subSkills: [
      'Garden maintenance',
      'Plant watering',
      'Lawn mowing',
      'Other',
    ],
  },
  {
    id: 'yoga-fitness',
    name: 'Yoga & Fitness',
    description: 'Yoga, fitness training',
    emoji: '🧘',
    subSkills: [
      'Yoga training',
      'Fitness training',
      'Personal training',
      'Other',
    ],
  },
  {
    id: 'astrology',
    name: 'Astrology & Vastu',
    description: 'Astrology, vastu help',
    emoji: '🔮',
    subSkills: [
      'Horoscope reading',
      'Vastu consultation',
      'Numerology',
      'Other',
    ],
  },
  {
    id: 'puja-services',
    name: 'Puja Services',
    description: 'Puja, religious services',
    emoji: '🙏',
    subSkills: [
      'Puja services',
      'Religious rituals',
      'Hawan',
      'Other',
    ],
  },
  {
    id: 'locksmith',
    name: 'Locksmith',
    description: 'Lock repair, emergency unlock',
    emoji: '🔑',
    subSkills: [
      'Door unlocking',
      'Lock repair',
      'Key duplication',
      'Other',
    ],
  },
  {
    id: 'bike-repair',
    name: 'Bike Repair',
    description: 'Bike service, repair',
    emoji: '🏍️',
    subSkills: [
      'Bike service',
      'Bike repair',
      'Puncture repair',
      'Other',
    ],
  },
  {
    id: 'car-wash',
    name: 'Car Wash',
    description: 'Car washing, cleaning',
    emoji: '🚗',
    subSkills: [
      'Car washing',
      'Car cleaning',
      'Car detailing',
      'Other',
    ],
  },
  {
    id: 'other',
    name: 'Other',
    description: 'Other quick help',
    emoji: '✨',
    subSkills: [
      'General help',
      'Other services',
    ],
  },
];

// Distance options in kilometers
export const DISTANCE_OPTIONS = [1, 3, 5, 10, 25, 50, 100];

// Get priority categories
export const PRIORITY_CATEGORIES = HELPER_TASK_CATEGORIES.filter(cat => cat.priority === 1);

// Get all category names
export const ALL_CATEGORY_NAMES = HELPER_TASK_CATEGORIES.map(cat => cat.name);

// Popular categories (for quick access)
export const POPULAR_CATEGORIES = PRIORITY_CATEGORIES;